ironjan/klausurtool-ror

.dockerignore
.gitignore
Dockerfile
README.Docker.md
config/database.yml
config/secrets.yml

Includes a dockerfile.
Also changed some settings to ease deployment with Docker.

Docker support

---

app/views/ausleihe/returning_form.html.erb

Added weigth and lender to returning form

---

.dockerignore

Sync dockerignore with gitignore

---

app/controllers/admin_lendouts_controller.rb
app/controllers/ausleihe_controller.rb

Archive is now ordered by date, desc

---

app/views/ausleihe/_archived_old_lend_out.html.erb
app/views/ausleihe/_old_lend_out.html.erb
app/views/layouts/application.html.erb

* After this, 0.0.10 can be released

Fixed some pre-release bugs

---

README.md

Also moved some todos to the issue tracker

Added note about the milestone names to README

---

Dockerfile

There actually seems to be a difference between precompiling for production and precompiling for development

Docker: actually compile production assets

---

CHANGELOG.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/toc.scss
app/assets/stylesheets/toc_print.scss
app/controllers/old_folders_controller.rb
app/views/application/_header.html.erb

Finalize pretty print

---

app/helpers/ausleihe_helper.rb
app/models/archived_old_lend_out.rb
app/models/concerns/lenders_and_receivers.rb
app/models/old_lend_out.rb
app/views/ausleihe/lending_form.html.erb
app/views/ausleihe/returning_form.html.erb

*  Values are loaded from database for people that did something in the last month
* Closes #3

Added often used values for lending

---

app/helpers/reminder_mails_helper.rb
app/views/ausleihe/_old_lend_out.html.erb
spec/helpers/reminder_mails_helper_spec.rb

* Refers to #140 
* Adds a mailto-Link to open an email template

Reminder mailto-Link

---

app/views/ausleihe/folder_details.html.erb
app/views/old_exams/_exams_table.html.erb

* Removed links from ausleihe to admin area

Fixed #150

---

CHANGELOG.md
app/views/old_folder_instances/_instances_table.html.erb
app/views/old_folders/_folder_instances.html.erb

* Fixes #143 and a bug that was discovered when doing so.
* Prepares release notes for 0.4.0

Fixing #143

---

app/controllers/ausleihe_controller.rb
config/routes.rb

* Further simplify this method

Reduce complexity of ausleihe_controller#switch

---

CHANGELOG.md

Prepared changelog

---

CHANGELOG.md
Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/cover.scss
app/controllers/ausleihe_controller.rb
app/controllers/internal/admin/print_controller.rb
app/views/internal/admin/print/cover.html.erb
app/views/old_folder_instances/_instances_table.html.erb
app/views/old_folders/_folder_instances.html.erb
app/views/old_folders/show.html.erb
config/routes.rb
spec/controllers/internal/admin/print_controller_spec.rb

* Fixes #52 
* Fixes #158 
**Open TODOs:**
* Print multiple Covers for folders with multiple instances (placed in "print actions" on folder details -> Move to new issue on merge)
* How important are "short names"? The current system doesn't have them because the old one didn't; the covers did have them though in some cases (e.g. EBKfS's true name is very long -> new issue)
* Currently "Prüfungsprotokollmappe" is written instead of "Prüfungsprotokolle". How important is this? -> new issue
* Code Review & Clean-Up

WIP: Beta – Print Covers

---

CHANGELOG.md
app/controllers/ausleihe_controller.rb
app/views/old_exams/edit.html.erb
app/views/old_exams/new.html.erb
app/views/old_folders/edit.html.erb
spec/views/old_folders/edit.html.erb_spec.rb

* Close all known defects that were known until 2016-04-18

WIP: 0 Defects

---

README.md
app/controllers/application_controller.rb
app/views/application/index.html.erb
app/views/old_exams/_exams_table.html.erb

Exam search for students

---

app/controllers/ausleihe_controller.rb

Fixed #147: Returning an already returned folder leads to exception

---

app/assets/stylesheets/application.scss
app/views/application/_header.html.erb

Added js & cookies warning to header

---

CHANGELOG.md

Added notes for 0.6.0

---

app/assets/javascripts/flashes.js
app/controllers/internal/admin/print_controller.rb
app/helpers/ausleihe_helper.rb
app/helpers/imt_to_name_helper.rb
app/helpers/old_folder_instances_helper.rb
app/models/old_folder.rb
app/views/ausleihe/lending_form.html.erb
config/application.rb
config/routes.rb
db/migrate/20160313124532_create_delayed_jobs.rb
spec/helpers/imt_to_name_helper_spec.rb

Code Cleanup and other things

---

app/views/application/_header.html.erb

Better wording for message.

---

config/deploy.rb

Added deploy.rb

---

app/models/old_folder.rb
app/views/old_exams/_exams_table.html.erb

Added exam type and barcodeId to search results
